---
abstract: 'Look up the country of an IPv4 address'
author:
  - 'Graciliano M. P. <gm@virtuasites.com.br>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-IPfree
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/bricas/geo-ipfree.git
version: 1.143630
