--- #YAML:1.0
name:               Geo-IPfree
version:            1.111650
abstract:           Look up the country of an IPv4 address
author:
    - Graciliano M. P. <gm@virtuasites.com.br>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Memoize:     0
    Test::More:  0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
